import { Link } from "react-router";

import LegalLayout from "../components/LegalLayout";

function Section({ title, children }) {
  return (
    <section>
      <h2 className="font-display text-xl font-bold tracking-tight text-stone-950 dark:text-stone-100">{title}</h2>
      <div className="mt-3 space-y-3">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <LegalLayout title="Terms of Use" updated="26 July 2026">
      <p>
        Pathwise is a university final-year project, built and operated for academic research and demonstration
        purposes. By creating an account, you agree to the terms below.
      </p>

      <Section title="The nature of this project">
        <p>
          This is not a commercial service. It may be reset, changed, or taken offline at any time as part of
          ongoing coursework, without notice.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You're responsible for keeping your password secure. Provide accurate information when registering, and
          use the platform for its intended purpose of browsing and evaluating course recommendations.
        </p>
      </Section>

      <Section title="Course listings">
        <p>
          Course details are drawn from third-party providers and are shown for research purposes. Pathwise doesn't
          control provider pricing, availability, or content — check the provider's own site before enrolling.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          Recommendations are generated by an experimental algorithm and may be inaccurate, incomplete, or
          unavailable at times. The platform is provided as-is, without guarantees of accuracy or uptime.
        </p>
      </Section>

      <Section title="Data">
        <p>
          See the <Link className="font-semibold text-terracotta-800 underline-offset-4 hover:underline dark:text-terracotta-400" to="/privacy">Privacy Policy</Link> for
          what data is collected and how to delete your account.
        </p>
      </Section>
    </LegalLayout>
  );
}
